### ISSUE TITLE
Recommended-CI preset does not remove log spam in CI

### ISSUE THREAD

**Issue by ST-DDT** [sibiraj-s/eslint-plugin-file-progress#12]
I tried using the new config preset in CI, but the log is still spammed by processing messages:

```txt
| Linting...
/ Linting...
- Linting...
\ Linting...
| Linting...
/ Linting...
- Linting...
\ Linting...
| Linting...
/ Linting...
- Linting...
\ Linting...
| Linting...
```

The presets removes the file from the message, but not the message itself.
In the current state, it doesn't feel like an improvement over the normal recommended preset.

Here are some logs for comparison:

- CI-Preset: https://github.com/faker-js/faker/actions/runs/11712439536/job/32623113396?pr=3252#step:6:11
- Normal-Preset: https://github.com/faker-js/faker/actions/runs/11712327435/job/32622732784?pr=3252#step:6:11

Maybe the following preset definition solve the issue?

````ts
  'recommended-ci': {
    name: 'progress/recommended-ci',
    plugins: {
      progress: plugin
    },
    rules: {
      "progress/activate": process.env.CI === 'true' ? 0 : 2
    },
  }
````

---

 Found in:

- https://github.com/faker-js/faker/pull/3252

**Comment by sibiraj-s** [comment]
Should be fixed in v3.0.1.
