### ISSUE TITLE
Node 18 is not EOL yet

### ISSUE THREAD

**Issue by ST-DDT** [sibiraj-s/eslint-plugin-file-progress#9]
I noticed, that you have dropped Node 18 support in v2.0.0 release.

Node 18 isn't EOL yet and won't be until April 2025:

- https://endoflife.date/nodejs

Since many libraries cannot drop Node support ahead of time and renovate keeps our dependencies always up to date, it would be nice, if you could add Node 18 back to the supported engines field.

Or are there Node 20 only features that you use preventing that?

**Comment by sibiraj-s** [comment]
My bad, it was not intended, will add the support range same as eslint 9 `^18.18.0, ^20.9.0, or >=21.1.0`

**Comment by sibiraj-s** [comment]
Should be fixed in v2.0.1
